### ISSUE TITLE
Default value not changed

### ISSUE THREAD

**Issue by pgpleroux** [perseas/Pyrseas#112]
Table looks like this:
Table "public.foobar"
 active | character varying(1) | default 'Y'::character varying

Output from dbtoyaml 
  table foobar:
    columns:
    - active:
        default: '''N''::character varying'
        type: character varying(1)

yamltodb dbase1 temp.yaml

Reports no change

**Comment by jmafc** [comment]
A quick look at the code (https://github.com/perseas/Pyrseas/blob/master/pyrseas/dbobject/column.py lines 162-166) shows that we took care of a new default being specified or an existing default being dropped but we missed checking for a change in the default. It shouldn't be difficult to fix. I'll try to take care of it early next week.
