### ISSUE TITLE
yamltodb 0.7.2 does not quote column names  when creating "ALTER TABLE DROP COLUMN ..." sql statements.

### ISSUE THREAD

**Issue by squareproton** [perseas/Pyrseas#114]
This causes a problem with column names in mixedCase.

Let me know if you'd like a testcase.

**Comment by jmafc** [comment]
It's a pretty straighforward fix: in `pyrseas/dbobject/column.py`, line 105 (last line of Column.drop) should use `quote_id(self.name)`.
