### ISSUE TITLE
Primary key changes

### ISSUE THREAD

**Issue by pgpleroux** [perseas/Pyrseas#115]
Added a primary key - column created, but primary key not updated.

And thanks for the software - in spite of a few small things it is probably the best of the lot. 
But: I am using apgdiff to keep an eye on Pyeseas :-)

# Old schema
CREATE TABLE server (
    server character varying(64) NOT NULL,
    fqdn character varying(64)
);
CREATE TABLE server_service (
    server character varying(64) NOT NULL,
    service character varying(64) DEFAULT 'service0'::character varying NOT NULL,
    instance integer NOT NULL
);
ALTER TABLE ONLY server
    ADD CONSTRAINT server_pkey PRIMARY KEY (server);
ALTER TABLE ONLY server_service
    ADD CONSTRAINT server_service_pkey PRIMARY KEY (server, service);
ALTER TABLE ONLY server_service
    ADD CONSTRAINT server_service_server_fkey FOREIGN KEY (server) REFERENCES server(server);

# New schema
CREATE TABLE server (
    server character varying(64) NOT NULL,
    fqdn character varying(64)
);

CREATE TABLE server_service (
    server character varying(64) NOT NULL,
    service character varying(64) DEFAULT 'service0'::character varying NOT NULL,
    instance integer NOT NULL
);
ALTER TABLE ONLY server
    ADD CONSTRAINT server_pkey PRIMARY KEY (server);
ALTER TABLE ONLY server_service
    ADD CONSTRAINT server_service_pkey PRIMARY KEY (server, service, instance);
ALTER TABLE ONLY server_service
    ADD CONSTRAINT server_service_server_fkey FOREIGN KEY (server) REFERENCES server(server);

**Comment by jmafc** [comment]
Thanks for keeping us honest with apgdiff :-)

If you look at `pyrseas/dbobject/constraint.py`, in PrimaryKey.diff_map, you'll notice that this is one of the TODOs: `TODO: to be implemented (via ALTER DROP and ALTER ADD)`.  That TODO has been there for quite some time. It seems to me that it shouldn't be too difficult to implement now that we have some of the mechanisms that weren't there initially.  It's a matter of detecting the difference in the PK, and the calling `self.drop()` and `inpk.add()`. @richardolsson is this perhaps something that you could help with?

**Comment by richardolsson** [comment]
Sure I can take a look at this. Might be a good first task to get properly acquainted with the codebase.

**Comment by jmafc** [comment]
OK. I don't know what your preferred development approach is, but I would suggest first adding a unit test, e.g., `test_change_primary_key` to PrimaryKeyToSqlTestCase in `pyrseas/dbobject/test_constraint.py`.

**Comment by pgpleroux** [comment]
Will see if I can figure something out (please don't tell any Perl people
that I am going to use Python :-))

Regards
Pieter

On 20 February 2015 at 09:46, Joe Abbate <notifications@github.com> wrote:

> Thanks for keeping us honest with apgdiff :-)
>
> If you look at pyrseas/dbobject/constraint.py, in PrimaryKey.diff_map,
> you'll notice that this is one of the TODOs: TODO: to be implemented (via
> ALTER DROP and ALTER ADD). That TODO has been there for quite some time.
> It seems to me that it shouldn't be too difficult to implement now that we
> have some of the mechanisms that weren't there initially. It's a matter of
> detecting the difference in the PK, and the calling self.drop() and
> inpk.add(). @richardolsson <https://github.com/richardolsson> is this
> perhaps something that you could help with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perseas/Pyrseas/issues/115#issuecomment-75132492>.
>



-- 
Pieter le Roux

**Comment by jmafc** [comment]
Pieter, just to be clear: my previous comment was in response to Richard. If you do want to attempt to fix this yourself, please try and coordinate with him (unless you're doing it purely to learn a better language :-)).

**Comment by richardolsson** [comment]
@jmafc: Sure, sounds like a reasonably approach. First of all I needed to get the test suite to run at all. I had some problems following the testing instructions in the docs but finally got it to work in a dockerized environment (https://github.com/richardolsson/pyrseas-testenv) and will proceed with actual development next. Will keep you posted!
