### ISSUE TITLE
Wrong sorting order for privileges and options in yaml file

### ISSUE THREAD

**Issue by darthunix** [perseas/Pyrseas#141]
I have two databases with the same schema. First database is used like trunk. Second database for development some feature (lets call it dev) . 

1. I add a function to a trunk database and commit yaml file to trunk branch in SVN.
2. Then I merge yaml file from trunk to dev branch in SVN to get added function. At this moment I get an annoying thing: attributes in some foreign data wrappers and functions are sorted in wrong order. Because of this PyCharm marks this parts of yaml file like conflicts to solve, though the objects are equivalent. 

Example 1. Wrong option order in foreign data wrapper.
**trunk:**
foreign data wrapper plproxy:
...
      quota:
        options:
        _- password=xxx
        - user=quota_
**dev:**
foreign data wrapper plproxy:
...
      quota:
        options:
        _- user=quota
        - password=xxx_

Example 2. Wrong privileges order in function.
**trunk:**
function donequota_preview(in_quotaid uuid):
...
    privileges:
    _- quota:
      - execute
    - PUBLIC:
      - execute_
    - lpu:
      - execute
**dev:**
function donequota_preview(in_quotaid uuid):
...
    _privileges:
    - PUBLIC:
      - execute
    - quota:
      - execute_
    - lpu:
      - execute

I have faced only with problems in function and wrapper order. Using Pyseas r0.7 from github. Is it possible to fix somehow the order of this parts in yaml file?

**Comment by jmafc** [comment]
In order to get a consistently ordered privilege list, I believe we'd have to modify `DbObject.map_privs` (in `pyrseas/dbobject/__init__.py` to sort the list by user, before it's returned. To get the options for FDWs is trickier, but it involves changing `pyrseas/dbobject/foreign.py`.

**Comment by darthunix** [comment]
Ok, I'll send you push request))

**Comment by jmafc** [comment]
Fixed by change d612a8f in r0.7.
