### ISSUE TITLE
How to config dsn for running pytest?

### ISSUE THREAD

**Issue by darthunix** [perseas/Pyrseas#143]
I don't know Python very good, so I have faced a problem trying to run tests for Pyrseas. They all fail because of using  _dsn = 'port=5432 dbname=postgres user=darthunix', database = None, user = None
password = None, host = None, port = None_. I don't like the idea to install PostgreSQL on my laptop's core system. For testing purpose I always use LXC container, so I want to change default dsn in tests. How can I run tests with another dsn?

**Comment by jmafc** [comment]
The answers are mostly in `pyrseas/testutils.py`, starting at line 42. You'll see you can define various environment variables such as `PYRSEAS_TEST_HOST to modify the values that are generated for the dsn. This is also mentioned in the [Testing](https://pyrseas.readthedocs.io/en/latest/testing.html) page of the documentation. If you think the instructions should be expanded, like giving an example of what to do, please let me know.

**Comment by darthunix** [comment]
Thanks, shame on me)) Everything was obvious!
