### ISSUE TITLE
KeyError: ('pglogical', 'truncate_trigger_add', '')

### ISSUE THREAD

**Issue by maajeck** [perseas/Pyrseas#151]
Hi,

I get the following error when running dbtoyaml -O -x -N pglogical demo

```
Traceback (most recent call last):
  File "/usr/local/postgresql-9.5/bin/dbtoyaml", line 9, in <module>
    load_entry_point('Pyrseas==0.7.2', 'console_scripts', 'dbtoyaml')()
  File "/usr/local/postgresql-9.5/lib/python2.7/site-packages/Pyrseas-0.7.2-py2.7.egg/pyrseas/dbtoyaml.py", line 49, in main
    dbmap = db.to_map()
  File "/usr/local/postgresql-9.5/lib/python2.7/site-packages/Pyrseas-0.7.2-py2.7.egg/pyrseas/database.py", line 269, in to_map
    self.from_catalog()
  File "/usr/local/postgresql-9.5/lib/python2.7/site-packages/Pyrseas-0.7.2-py2.7.egg/pyrseas/database.py", line 179, in from_catalog
    self._link_refs(self.db)
  File "/usr/local/postgresql-9.5/lib/python2.7/site-packages/Pyrseas-0.7.2-py2.7.egg/pyrseas/database.py", line 140, in _link_refs
    db.functions.link_refs(db.eventtrigs)
  File "/usr/local/postgresql-9.5/lib/python2.7/site-packages/Pyrseas-0.7.2-py2.7.egg/pyrseas/dbobject/function.py", line 329, in link_refs
    func = self[(sch, fnc[:-2], '')]
KeyError: ('pglogical', 'truncate_trigger_add', '')
```

To fix this I used I changed in pyrseas/dbobject/function.py
```
def link_refs(self, dbeventtrigs):
        """Connect event triggers to the functions executed

        :param dbeventtrigs: dictionary of event triggers

        Fills in the `event_triggers` list for each function by
        traversing the `dbeventtrigs` dictionary.
        """
        for key in dbeventtrigs:
            evttrg = dbeventtrigs[key]
            (sch, fnc) = split_schema_obj(evttrg.procedure)
            if not fnc[:-2]:
                func = self[(sch, fnc[:-2], '')]
                if not hasattr(func, 'event_triggers'):
                    func.event_triggers = []
                func.event_triggers.append(evttrg.name)
```

This solved the issue, if you agree can commit it to the master?

Regards

**Comment by jmafc** [comment]
I'll take a look later and let you know.

**Comment by jmafc** [comment]
I'm having trouble accepting your change because it seems to simply bypass code that was supposed to have a purpose.  Could you please make the following change:
```diff
@@ -325,6 +325,8 @@ class ProcDict(DbObjectDict):
         """
         for key in dbeventtrigs:
             evttrg = dbeventtrigs[key]
+            print("evttrg=%s" % evttrg.__dict__)
+            print("self.keys()=%s" % self.keys())
             (sch, fnc) = split_schema_obj(evttrg.procedure)
```
and run it against your demo database, either with the change above or the original code (maybe easier since it will stop at the error before printing the info).

**Comment by jmafc** [comment]
For some reason, either GitHub didn't send an email for your reply above or if it did, it somehow got lost. Anyway, I'll take a look Monday and get back to you.

**Comment by jmafc** [comment]
So, breaking down the output, the `evttrg` (apparently the only one) is named `pglogical_truncate_trigger_add` and it refers to procedure `pglogical.truncate_trigger_add`. However, the `ProcDict` only has the following keys:
```python
[
  (u'public', u'terminate_backend', u'inputpid integer'),
  (u'public', u'pg_stat_get_activity_all', ...),
  (u'public', u'cancel_backend', u'inputpid integer'),
  (u'public', u'replicate_ddl', u'p_relnamespace pg_catalog.name, p_relname pg_catalog.name, p_command text')
]
```
In other words, no functions from a `pglogical` schema. This means the `ProcDict` query starting at about line 230 isn't fetching all the functions we want (or the `_from_catalog` method is discarding a function). Could you please execute the query to try determine what is wrong?  If it only returns the four functions above we'll have to look at what is causing the exclusion of the event trigger procedure.

**Comment by maajeck** [comment]
I did some more investigation and found the reason for the problem. The function was triggered by an event-trigger. So I changed 'pyrseas/dbobject/eventtrig.py' and it works again, without the change in function.py.

```
 cls = EventTrigger
    query = \
        """SELECT evtname AS name, evtevent AS event, rolname AS owner,
                  evtenabled AS enabled, evtfoid::regprocedure AS procedure,
                  evttags AS tags,
                  obj_description(t.oid, 'pg_event_trigger') AS description
           FROM pg_event_trigger t
                JOIN pg_roles ON (evtowner = pg_roles.oid)
           WHERE t.oid NOT IN (SELECT objid FROM pg_depend WHERE deptype = 'e' AND refclassid = 'pg_extension'::regclass)
           ORDER BY 1"""
```

Thanks for looking into this.

**Comment by jmafc** [comment]
No, thanks to you for helping me to correct this. Before I make the change I'd appreciate you to confirm a couple of things. Please issue the query `SELECT refclassid::regclass FROM pg_depend WHERE deptype = 'e';` to confirm all rows have `refclassid` equal to `pg_extension` (in which case the extra test is unnecessary--this seems to be the case based on how `deptype = 'e'` is described in the docs).

Second, I'd like to see the output of `SELECT * FROM pg_event_trigger` from your database, which appears to have the `pglogical` extension and perhaps others. Event triggers are relatively recent and although we have some tests in `tests/dbobject/test_eventtrig.py`, they're  very simple (and obviously didn't catch this defect). I would like to create one or two more and hopefully your output may help.

**Comment by maajeck** [comment]
I ran the query `SELECT refclassid::regclass FROM pg_depend WHERE deptype = 'e';`
which gave only the result `pg_extension` (389 rows).

```
psp=# SELECT oid,* FROM pg_event_trigger;
  oid  |              evtname               |    evtevent     | evtowner | evtfoid | evtenabled |              evttags
-------+------------------------------------+-----------------+----------+---------+------------+------------------------------------
 71425 | pglogical_truncate_trigger_add     | ddl_command_end |       10 |   71424 | A          | {"CREATE TABLE","CREATE TABLE AS"}
 71427 | pglogical_dependency_check_trigger | sql_drop        |       10 |   71426 | A          |
(2 rows)

psp=# select *,refclassid::regclass from pg_depend where objid in (71425,71427) ;
 classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype |  refclassid
---------+-------+----------+------------+----------+-------------+---------+--------------
    3466 | 71425 |        0 |       1255 |    71424 |           0 | n       | pg_proc
    3466 | 71425 |        0 |       3079 |    71284 |           0 | e       | pg_extension
    3466 | 71427 |        0 |       1255 |    71426 |           0 | n       | pg_proc
    3466 | 71427 |        0 |       3079 |    71284 |           0 | e       | pg_extension
(4 rows)
```

Better tests are always good. If everything is ok, can you branch.

Thanks for all you help.

**Comment by jmafc** [comment]
OK, it appears that in order to create a test to get those `deptype = 'e'` rows in `pg_depend`, we'd have to create an extension (or install one) that created an event trigger. That may be too much for a unit test, so I'll pass on adding one.
