### ISSUE TITLE
set sequence owner

### ISSUE THREAD

**Issue by mat813** [perseas/Pyrseas#157]
Hi,

I just started using pyrseas on an old project and I'm cleaning things up, I found a couple of sequences that were not "owned", so, I edited the yaml and added the correct data:

```diff
--- a/db/metadata/schema.public/sequence.logs_id_log_seq.yaml
+++ b/db/metadata/schema.public/sequence.logs_id_log_seq.yaml
@@ -4,6 +4,8 @@ sequence logs_id_log_seq:
   max_value: null
   min_value: null
   owner: mat
+  owner_column: id_log
+  owner_table: logs
   privileges:
   - mat:
     - all
```

but when I run yamltodb, it does not say anything, it should say something along the lines of:

```sql
ALTER SEQUENCE public.logs_id_log_seq OWNED BY public.logs.id_log;
```

**Comment by jmafc** [comment]
Confirmed. In `pyrseas/dbobject/table.py`, `Sequence.diff_map` the values for `owner_table` and `owner_column` are present at entry, but there is no logic to generate the `ALTER TABLE OWNED BY` statement. It should be a fairly straightforward addition.
