### ISSUE TITLE
schema 'public' should not be given special treatment

### ISSUE THREAD

**Issue by jmafc** [perseas/Pyrseas#176]
When `dbtoyaml` or `yamltodb` connect to a database, they issue a `set search_path to public, pg_catalog`. Thereafter, the schema `public` is given special treatment as the default schema for any object. This seems to lead to more problems than are worth the benefit of having a default schema. See further discussion of this with @dvarrazzo in issue #175. The recommendation is to drop this special casing.

**Comment by jmafc** [comment]
The source of the `set search_path` statement is `pg_dump` which influenced Pyrseas' initial design. When generating the dump script in a typical PG database, it issues the command above usually as the first and only `SET search_path` statement. However, in a multi-schema database (such as the one used by `autodoc`), `pg_dump` issues multiple SET search_path statements as can be seen below:
```sql
SET search_path = product, pg_catalog;
SET search_path = warehouse, pg_catalog;
SET search_path = inherit, pg_catalog;
SET search_path = product, pg_catalog;
SET search_path = store, pg_catalog;
SET search_path = warehouse, pg_catalog;
SET search_path = product, pg_catalog;
SET search_path = store, pg_catalog;
SET search_path = warehouse, pg_catalog;
SET search_path = product, pg_catalog;
SET search_path = store, pg_catalog;
SET search_path = warehouse, pg_catalog;
SET search_path = store, pg_catalog;
SET search_path = warehouse, pg_catalog;
```

**Comment by jmafc** [comment]
@dvarrazzo I started to make changes to address the subject issue. I only made two code changes:
```diff
diff --git a/pyrseas/database.py b/pyrseas/database.py
index 1675610..2a57458 100644
--- a/pyrseas/database.py
+++ b/pyrseas/database.py
@@ -61,11 +61,7 @@ class CatDbConnection(DbConnection):
     def connect(self):
         """Connect to the database"""
         super(CatDbConnection, self).connect()
-        try:
-            self.execute("set search_path to public, pg_catalog")
-        except:
-            self.rollback()
-            self.execute("set search_path to pg_catalog")
+        self.execute("set search_path to pg_catalog")
         self.commit()
         self._version = self.conn.server_version
 
diff --git a/pyrseas/dbobject/__init__.py b/pyrseas/dbobject/__init__.py
index a7ddb1e..0049ffd 100644
--- a/pyrseas/dbobject/__init__.py
+++ b/pyrseas/dbobject/__init__.py
@@ -545,13 +545,10 @@ class DbSchemaObject(DbObject):
         """Return the schema-qualified name of self or a related object
 
         :return: string
-
-        No qualification is used if the schema is 'public'.
         """
         if objname is None:
             objname = self.name
-        return self.schema == 'public' and quote_id(objname) \
-            or "%s.%s" % (quote_id(self.schema), quote_id(objname))
+        return "%s.%s" % (quote_id(self.schema), quote_id(objname))
 
     def unqualify(self):
         """Adjust the schema and table name if the latter is qualified"""
```
Then I started testing: `test_extension` and `test_schema` no probs (as expected). `test_table` (limiting it just to the `ToMap` cases gave a single error in https://github.com/perseas/Pyrseas/blob/72d205ff57264634254ba4ab402cbce06945cece/tests/dbobject/test_table.py#L60 The problem is essentially that, with the change to `DbSchemaObject.qualname()`, `dbtoyaml` now outputs the following (abbreviated):
```yaml
schema public:
...
  table t1:
...
  table t2:
...
  table t3:
...
    inherits:
    - public.t1
    - public.t2
```
whereas the test expects just `['t1', 't2']`. The new output looks somewhat redundant to me, since `table t3` is being described in the context (indented under) `schema public`.
Contrasting this with the `pg_dump` output, I also see:
```sql
CREATE TABLE t3 (
    c4 text
)
INHERITS (t1, t2);
```
This is possible because, prior to that statement, `pg_dump` has issued:
```sql
SET search_path = public, pg_catalog;
```
It would be nice to emulate this behavior. So I'm thinking of changing `DbSchemaObject.qualname()` to take a second `schema` argument, i.e., the schema of the object for which we're calling `qualname()`. Then I wouldn't need to change the expected test results (probably not only here, but in countless other places).

What do you think?

**Comment by tbussmann** [comment]
I like the general direction this is going and not special treating `public`. With a change like you are proposing, you are increasing locality and with that relocateability (restore into different schema). If you suppress the output of the schema in the yaml form, I think `yamltodb` on the other hand need to add it again when generating SQL, if not setting `search_path`s individually.

**Comment by jmafc** [comment]
I haven't explored the SQL generation side yet, but I suspect that setting `search_path`s (as `pg_dump` does) wouldl be another major effort since the topological sort gives us objects to alter as required, rather than nice single-schema streams, and it's questionable what is the benefit of individual `set search_path` before every namespace change (as seen in the previous `autodoc` comment) versus having explicit `schema_name.object_name` references in each DDL statement.

**Comment by jmafc** [comment]
@dvarrazzo @tbussmann 
A further complication on dealing with the `public` schema: when running, for example, `tests/dbobject/test_view.py` `test_map_view_table`, the view definition we currently expect is `SELECT ... FROM t1` but `pg_get_viewdef` gives us `SELECT ... FROM public.t1`. Of course, this is because the Pyrseas application connection has set `search_path` to just `pg_catalog` so the table *has* to be qualified.

The table gets created by default in `public` because the test connection creates the table and the view without qualification and has done a normal connection, meaning it that done `set search_path = '"$user",public'` because that's the default `postgresql.conf` instructs it to do. In most development and test environments, `postgresql.conf` will be untouched as far as this is concerned (i.e., `schema public`, iike it or not, *is* a special case in most environments).

There are several alternatives.
* Leave the test connection and the test object specifications as they are and only change the tests where needed. We could also verify that we're defaulting to `public`, or issue a `set search_path`, as part of the connection procedure.
* After connecting for testing, create a schema, say `sd` (or `default_schema` if we want to be verbose), and `set search_path` to it. therefore defaulting to creating unqualified objects in `sd`. This would have the advantage that the `PgTestDb.clear()` method could DROP CASCADE *all* schemas (right now it special-cases `public`--and `information_schema` becase we don't mess with the latter). Various tests would also have to be changed.
* Use a "$user" schema as the test default. Currently the `PyrseasTestCaser.setUp() method provides access to the connected username, which is used, for example, in testing privileges and with some work we could use it for this purpose.

I'm inclined to go with the second option, but would welcome opinions or other suggestions.

**Comment by dvarrazzo** [comment]
I would think it is no problem in changing the tests if they have to reflect the fact that now Pyrseas generates a different output, even more so if the output is semantically equivalent (given the interpretation context the tests previously assumed, i.e. `public` early in the path) and IMO qualitatively better (because the object definition is independent from the context and more robust to be used whatever the context is).

Just to chime in, as I hadn't left my comment yet about the topic: the solution pg_dump uses, i.e. potentially switching `search_path` for every object it generates, is absolutely terrible for any use case for the dump which is not just restoring the schema in its entirety. Some sysadmin colleagues of mine have tried to build some backup/check tools on top of `pg_dump` output and the statefulness of its output has made them ridiculously complex.

**Comment by jmafc** [comment]
I don't mind changing the tests to reflect new expected output/behavior. What I didn't like is having to sprinkle `public.<something>` all over the tests when the purpose was to *not* special-case the `public` schema. And without changes to `pyrseas/testutils.py`, that would still depend implicitly on the tester/developer not having a changed `postgresql.conf`. That's why I'm suggesting creating our own default schema (`sd`) and setting the `search_path` to it (and then sprinkling `sd.<something>` where needed in the tests).

**Comment by jmafc** [comment]
@dvarrazzo @tbussmann 
The proposed approach of trying to "unqualify" related objects as long as they're within the same schema as the "current" object breaks down in a number of cases, generally having to do with functions or operators.
The most problematic for now has to do with triggers and the procedures they execute. For example, given the following YAML output:
```yaml
schema sd:
  function f1():
    ...
  table t1:
  ...
    triggers:
      tr1:
        ...
        procedure: f1
```
The key is that `f1` not being qualified means it's actually `sd.f1()`. Note that internally the procedure is a (schema, function) tuple. However, if a trigger invokes something like `tsvector_update_trigger` the unqualified name leads to problems because it's interpreted as being in, say, schema `sd` when it's actually in `pg_catalog`.
There are several possibilities that come to mind as possible fixes.
1. Always output trigger procedures as qualified names, unless they're in `pg_catalog`.
2. Deal especially with `tsvector_update_trigger` and similar functions using a list or similar.
3. Search for a function, after it's "requalified" (in the SQL create/alter side) and if it's not found, drop the qualification.
4. Set search_path to nothing and then refactor everything again to deal with `pg_catalog` objects.

For now, unless someone shouts in the next day or so, I'll go with option 1.

**Comment by dvarrazzo** [comment]
> For now, unless someone shouts in the next day or so, I'll go with option 1.

+1

**Comment by jmafc** [comment]
I've submitted the changes for option 1 but the code for detecting whether we should split a possibly-qualified procedure is rather weak. Also, the code for qualifying/unqualifying, splitting/rejoining objects has become haphazard and inconsistent. And the functional tests have to be fixed, since there's now interaction between schemas `sd` and `public` when they're run in sequence.

**Comment by jmafc** [comment]
I've made changes to the functional tests so that the branch `schemapublic` passes all tests, except that there still two tests that are marked `xfail`. In theory, the branch could be merged into `master` so more people are exposed to the changes (and bugs not caught by the tests surface!).

As explained privately to @dvarrazzo, the tests that I had to mark `xfail` are `OperatorClassToSqlTestCase.test_create_operclass_default` in `test_operclass.py` and `BaseTypeToSqlTestCase.test_drop_type` in `test_type.py`. The presumed problem is that both tests create a SHELL type, then I/O functions, and then the final base type but `Database.dep_sorted` can't complete the topological sort and raises the exception "the objects dependencies graph has loops". This did not happen with the default schema being `public` apparently because the unqualified names somehow masked the problem.

All this reminded me of Post-Facto, which also had a topological sort. The source has been saved in https://bitbucket.org/fumanchu/postfacto, the sort is in `postfacto/differ.py`, is named `topo_sorted` and has a similar exception at the end: "Circular dependencies found".  I haven't compared it closely yet to Daniele's implementation but the exception does print out `remaining` which apparently is a list of objects that are depedent on one another. Maybe we need to add something similar to figure out or confirm what the problem is.

**Comment by tbussmann** [comment]
> 4. Set search_path to nothing and then refactor everything again to deal with pg_catalog objects.

While reading through the massive upstream change-set to `pg_dump` to mitigate an upcoming issue,  I tend to the conclusion that actually that 4th option seems the way to go for Pyrseas as well. It gets even recommended to issue `SELECT pg_catalog.set_config('search_path', '', false)` right after connect for 3rd party tools and to qualify everything.

**Comment by jmafc** [comment]
Tobias, in our case, we generally shy away from retrieving anything that is in `pg_catalog` (and that does have some downsides that we yet have to explore--see for example #175). In any case, right now we're qualifying like over 98% of everything (except as noted above when we're in the context of the qualifying schema in YAML).
