### ISSUE TITLE
[Q] boileplate example / tutorial

### ISSUE THREAD

**Issue by vladp** [perseas/Pyrseas#181]
Hello
starting a new postgresql based project.
Is there good boilerplate/template/working example with non trivial db object (jsonb fields, procedures, etc), that I could start from ?

thank you

**Comment by jmafc** [comment]
This isn't directly related to Pyrseas but I'll answer anyway. Probably the best well known "sample database" for Postgres is `pagila` which you can find at https://github.com/xzilla/pagila. Pyrseas uses an older version of that in its `tests/functional`, where you will also find the `autodoc` database which has interesting cross-schema referencing. Pagila doesn't have jsonb fields but it does have fairly advanced Postgres features such as range partitoning.
