### ISSUE TITLE
Unable to add new table in --multiple-files mode

### ISSUE THREAD

**Issue by sgurusharan** [perseas/Pyrseas#194]
Create a multiple-files yaml dump from a database using:
`dbtoyaml --config ./config.yaml --multiple-files testdb`

Create a new yaml file inside the metadata/schema.public/ directory with the name: table.testtable.yaml and add the below contents:
```
table taskaction:
  columns:
  - id:
      not_null: true
      type: bigint
  owner: postgres
```

Invoke yamltodb to view the SQL statements for the change:
`yamltodb --config ./config.yaml --multiple-files testdb`

No changes are seen.

Other Info:
`yamltodb --version`: yamltodb 0.8.0

**Comment by jmafc** [comment]
I'm unable to reproduce the problem. When I try it, I see
```sql
CREATE TABLE public.taskaction (
    id bigint NOT NULL);
```
However, although you specified `--config ./config.yaml` you did not show what is in that `config.yaml`, so I ran my commands without that option.

**Comment by sgurusharan** [comment]
My mistake. I had copied the yaml from an existing table and failed to rename the table name inside the yaml file. Hence closing this.
