### ISSUE TITLE
cannot yamltodb Postgresql 11

### ISSUE THREAD

**Issue by vladp** [perseas/Pyrseas#195]
Hello, 
I saved my schema with dbtoyaml from PG 10,
now updated to PG11, recreated database and wanted to apply the saved schema
to new database

However I am getting errors. I have never seen those before while using the package on PG10.
(the env is:  Linux Fedora 27 , python3, pyrseas 0.8, psycopg2 2.7.4 )

```

Traceback (most recent call last):
  File "/usr/local/bin/yamltodb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/pyrseas/yamltodb.py", line 50, in main
    stmts = db.diff_map(inmap)
  File "/usr/local/lib64/python3.6/site-packages/pyrseas/database.py", line 510, in diff_map
    self.from_catalog()
  File "/usr/local/lib64/python3.6/site-packages/pyrseas/database.py", line 348, in from_catalog
    self.db = self.Dicts(self.dbconn, single_db)
  File "/usr/local/lib64/python3.6/site-packages/pyrseas/database.py", line 100, in __init__
    self.functions = ProcDict(dbconn)
  File "/usr/local/lib64/python3.6/site-packages/pyrseas/dbobject/__init__.py", line 633, in __init__
    self._from_catalog()
  File "/usr/local/lib64/python3.6/site-packages/pyrseas/dbobject/function.py", line 614, in _from_catalog
    for obj in self.fetch():
  File "/usr/local/lib64/python3.6/site-packages/pyrseas/dbobject/__init__.py", line 683, in fetch
    data = self.dbconn.fetchall(self.query)
  File "/usr/local/lib/python3.6/site-packages/pgdbconn/dbconn.py", line 107, in fetchall
    curs = self.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/pgdbconn/dbconn.py", line 81, in execute
    raise exc
  File "/usr/local/lib/python3.6/site-packages/pgdbconn/dbconn.py", line 77, in execute
    curs.execute(query, args)
  File "/usr/local/lib64/python3.6/site-packages/psycopg2/extras.py", line 144, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: column "proisagg" does not exist
LINE 17:               AND NOT proisagg
                               ^
HINT:  Perhaps you meant to reference the column "p.prolang".

```
could be similar to 
https://github.com/jOOQ/jOOQ/issues/7785

**Comment by jmafc** [comment]
@vladp Yep, if you compare the PG 10 version of `pg_proc` with the PG 11 version, you'll see that both `proisagg` and `proiswindow` are gone and `prokind` replaces them (and adds type `p` for the new PROCEDUREs). At the very least, both queries in `pyrseas/dbobject/function.py` will need to have PG 11 versions that replace the `proisagg` by `prokind = a`.
In previous years, I used to install a beta before the final release. This year, as explained in https://pyrseas.wordpress.com/2018/09/12/the-future-of-pyrseas-revisited/, I've taken a much less active approach. However, I did install PG 11 on Friday, so I guess I'll have to bite the bullet and spend some time at least ensuring the current and functional tests all run and fixing any errors.

**Comment by jmafc** [comment]
Thanks for the vote of confidence, Vladislav. As I said, I will do something about PG 11, over the coming week or two. I'll see what I can add to the readme regarding the reduced support level.

As for what other people use, in the early days of the project I had done a survey of other tools and published it in my blog (see https://pyrseas.wordpress.com/schema-vc/), but as you can see it hasn't been updated in the last four years. From what I hear, Sqitch is rather popular among PG users, but it does require that you code your changes in SQL (and code to backout changes as well). Schema migration tools that depend on specific programming frameworks or ORMs are supposedly popular too.

**Comment by jmafc** [comment]
I've made the change to `dbobject/function.py` and ran the tests in `tests/dbobject` and except for a version change (1.3 to 1.4) in mapping extensions, they all pass against PG 11. I'll add the extension change, cleanup the function code, run all the tests again and probably commit the changes late tonight.

**Comment by vladp** [comment]
very much appreciated. thank you

**Comment by jmafc** [comment]
I've comitted the changes but there's a strange issue with `test_column.py` in `test_create_column_identity`. It only happens when it runs under Python 2.7: it creates the columns in inverse order, i.e., c2, c1, although they're specified in a Python list (technically a sequential structure!). It also happens against PG 10, so it's unrelated to PG 11 changes. Will submit it now so that the tests can run on Travis which is a somewhat different environment.

**Comment by jmafc** [comment]
The tests ran fine on Travis, so perhaps the column_identity problem is just an issue with my slightly more bleeding edge versions of Python 2.7 and py.test.

**Comment by vladp** [comment]
it worked for me now. Thank you.
It took me a while to figure out how to install an unreleased python package (and I messed up my python3 install, all the modules, and even the Fedora's dnf).
But just doing 
`pip3 install git+https://github.com/perseas/Pyrseas.git`

allowed me to run your changes, and they worked.
