### ISSUE TITLE
feature request: running a manual patch file

### ISSUE THREAD

**Issue by charles-cooper** [perseas/Pyrseas#223]
Similar to the rename function, but could run an arbitrary patch file. This would be helpful for cases when pyrseas isn't doing exactly the right thing. The patch file would run before any catalog queries execute and in the same transaction as all the generated DDL statements. (I can flesh this out more if needed)

**Comment by jmafc** [comment]
This looks very much like #197, which is still open and was fleshed out quite a bit back when it was opened. Unfortunately, I haven't had much time (or frankly, interest) to pursue further enhancements on the Python codebase. If you agree that your request is similar enough to #197, I would suggest closing this and adding further info under that issue.

**Comment by charles-cooper** [comment]
Thanks for the info. I'll close this and add any additional comments on #197
