### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by benjamin-kirkbride** [perseas/Pyrseas#240]
I have some more discussion/informal type things I'd like to ask/discuss. Any chance we open up https://docs.github.com/en/discussions for the purpose? Thanks!

**Comment by jmafc** [comment]
I think I've just opened, but I'm not sure. The intro video says that one can convert an issue to a discussion but can't see how that's done. Please try to add a discussion. If it doesn't work, I'll open one, if you give some kind of title.

**Comment by jmafc** [comment]
Closing since discussions work.
