### ISSUE TITLE
Primary keys (possibly all unique constraints) need to be created before views

### ISSUE THREAD

**Issue by denaje** [perseas/Pyrseas#72]
Pyrseas: 0.7.0b1
PostgreSQL: 9.3.1
Python: 3.3

It seems as though the order of creation of items is:
- Tables
- Views
- Constraints

This causes a problem if the creation of a view depends on constraints on the tables. For instance, if a view does something like (simplified example):

```
CREATE VIEW my_schema.my_view AS
    SELECT u.id, u.name
    FROM users u
    GROUP BY u.id;
```

Then Postgres will complain

```
ERROR:  column "u.name" must appear in the GROUP BY clause or be used in an aggregate function
```

This is not a problem if the PK constraint on users.id is created, because Postgres is smart enough to figure out that grouping on a unique constraint will ensure uniqueness in the result set. However, the PK constraint is not created at the time the view is created, causing the error.

**Comment by jmafc** [comment]
Issue has been resolved by the dependency tracking changes. Test added to `tests/dbobject/test_view.py` to confirm.
