### ISSUE TITLE
dbtoyaml can't represent an index on a materialized view

### ISSUE THREAD

**Issue by rhunwicks** [perseas/Pyrseas#82]
I've got a materialized view, and then I have defined an index on the materialized view.   When I run `dbtoyaml` I get:

```
yaml.representer.RepresenterError: cannot represent an object: <pyrseas.dbobject.index.Index object at 0x10a92abd0>
```

**Comment by rhunwicks** [comment]
Joe

Did the other side of this ever get built - I now have a situation where I would like to create the indexes on a materialized view from the yml.

Regards

Roger

**Comment by jmafc** [comment]
Sorry, Roger, I'm afraid not yet. Reopening issue.
