### ISSUE TITLE
yamltodb 0.7.1 attempts to create already existing table when postgres casts are involved

### ISSUE THREAD

**Issue by squareproton** [perseas/Pyrseas#86]
To reproduce execute the following sql and build test_cast.yml with dbtoyaml.

```
DROP SCHEMA IF EXISTS test_cast CASCADE;
CREATE SCHEMA test_cast;
SET search_path TO test_cast;

CREATE TABLE t1 (
    id integer
);

CREATE VIEW v1 AS
SELECT * FROM t1;

CREATE FUNCTION v1_to_t1(v1) RETURNS t1 LANGUAGE plpgsql AS $_$
DECLARE
    o t1;
BEGIN
    o := ROW($1.id)::t1;
    RETURN o;
END
$_$;

CREATE CAST (v1 AS t1) WITH FUNCTION v1_to_t1(v1);
```

Drop the view `DROP VIEW v1 CASCADE;` which will remove the function and cast declaration.

Running `yamltodb -o /dev/stdout test_cast test_cast.yml` yeilds

```
SET check_function_bodies = false;

CREATE TABLE test_cast.t1 (
    id integer);

ALTER TABLE test_cast.t1 OWNER TO unit;

CREATE FUNCTION test_cast.v1_to_t1(test_cast.v1) RETURNS test_cast.t1
    LANGUAGE plpgsql
    AS $_$
DECLARE
    o t1;
BEGIN
    o := ROW($1.id)::t1;
    RETURN o;
END
$_$;

ALTER FUNCTION test_cast.v1_to_t1(test_cast.v1) OWNER TO unit;

CREATE VIEW test_cast.v1 AS
    SELECT t1.id
   FROM test_cast.t1;

ALTER VIEW test_cast.v1 OWNER TO unit;

CREATE CAST (test_cast.v1 AS test_cast.t1)
    WITH FUNCTION test_cast.v1_to_t1(test_cast.v1);
```

This will fail for two reasons.
1. The table t1 already exists and hasn't changed.
2. The function v1_to_t1 cannot be created before v1 as it uses the v1 type in its declaration.

Tested on pyrseas v0.7.1 and postgres 9.2.6.

**Comment by jmafc** [comment]
@squareproton This has been fixed in the current master branch, as a result of the dependency tracking changes.  `yamltodb` now produces `CREATE VIEW`, `CREATE FUNCTION` and `CREATE CAST` in that order (with the `CREATE TABLE`). I will try to add a test to further verify this and avoid future regressions, but perhaps you can try it on your actual examples.
