### ISSUE TITLE
yamltodb 0.7.1 does not does not pickup changes to enums

### ISSUE THREAD

**Issue by squareproton** [perseas/Pyrseas#87]
```
DROP SCHEMA IF EXISTS test_enum CASCADE;
CREATE SCHEMA test_enum;
SET search_path TO test_enum;
CREATE TYPE test AS ENUM ('one', 'two');
```

dbtoyaml produces

```
...
schema test_enum:
  owner: unit
  type test:
    labels:
    - one
    - two
```

Add value to enum `ALTER TYPE test ADD VALUE 'three';`. Execute yamltodb with our previously generated yaml yeilds a empty result. Dropping the type produces the `CREATE TYPE` expression you'd expect so it seems this type of DDL is covered by Pyrseas.

Pyrseas 0.7.1, postgres 9.2.6

**Comment by pumazi** [comment]
I can confirm this.
